export const sneakerData  = [
    {
        id:1,
        name: "JORDAN 1 OFF-WHITE CHICAGO",
        price: 4000,
        category: "Off white",
        img: "https://katanasneaker.vercel.app/assets/img/SNEAKERWEPB3/AIR%20JORDAN%201%20RETRO%20HIGH%20OFF-WHITE.webp",
        rating: 5,
    },
    {
        id:2,
        name: "ADIDAS RESPONSE BAD BUNNY",
        price: 220,
        category: "Adidas",
        img: "https://katanasneaker.vercel.app/assets/img/SNEAKERWEPB3/ADIDAS%20RESPONSE%20BAD%20BUNNY%20YELLOW.webp",
        rating: 4,
    },
    {
        id:3,
        name: "ADIDAS ADILETTE 22 SLIDES",
        price: 50,
        category: "Adidas",
        img: "https://katanasneaker.vercel.app/assets/img/SNEAKERWEPB3/ADILETTE%2022%20SLIDES%20ST.webp",
        rating: 6,
    },
    {
        id:4,
        name: "DUNK LOW UNDEFEATED",
        price: 107,
        category: "Nike",
        img: "https://katanasneaker.vercel.app/assets/img/SNEAKERWEPB3/DUNK%20LOW%20UNDEFEATED.webp",
        rating: 7,
    },
    {
        id:5,
        name: "AIR FORCE 1 LOW SKELETON",
        price: 182,
        category: "Nike",
        img: "https://katanasneaker.vercel.app/assets/img/SNEAKERWEPB3/AIR%20FORCE%201%20LOW%20PURPLE%20SKELETON.webp",
        rating: 8,
    },
    {
        id:6,
        name: "JORDAN 5 RETRO OFF-WHITE",
        price: 450,
        category: "Off white",
        img: "https://katanasneaker.vercel.app/assets/img/SNEAKERWEPB3/AIR%20JORDAN%205%20RETRO%20OFF-WHITE.webp",
        rating: 9,
    },
    {
        id:7,
        name: "DUNK LOW TRAVIS SCOTT",
        price: 1370,
        category: "Nike",
        img: "https://katanasneaker.vercel.app/assets/img/SNEAKERWEPB3/NIKE%20SB%20DUNK%20TRAVIS%20SCOTT.webp",
        rating: 10,
    
    },
    {
        id:8,
        name: "ADIDAS FORUM BAD BUNNY",
        price: 300,
        category: "Adidas",
        img: "https://katanasneaker.vercel.app/assets/img/SNEAKERWEPB3/FORUM%20LOW%20BAD%20BUNNY%20BACK%20TO%20SCHOOL.webp",
        rating: 9,
    },
    {
        id:10,
        name: "YEEZY BOOST 350 V2 BELUGA",
        price: 241,
        category: "Yeezy",
        img: "https://katanasneaker.vercel.app/assets/img/SNEAKERWEPB3/YEEZY%20BOOST%20350%20V2%20BELUGA.webp",
        rating: 4,
    },
    {
        id:11,
        name: "ADIDAS OZWEEGO CALL OF DUTY",
        price: 200,
        category: "Adidas",
        img: "https://katanasneaker.vercel.app/assets/img/SNEAKERWEPB3/OZWEEGO%20CALL%20OF%20DUTY.webp",
        rating: 3,
    
    },
    {
        id:12,
        name: "ADIDAS SUPERSTAR THE SIMPSONS",
        price: 100,
        category: "Adidas",
        img: "https://katanasneaker.vercel.app/assets/img/SNEAKERWEPB3/ADIDAS%20SUPERSTAR%20THE%20SIMPSONS.webp",
        rating: 4,
    },
    {
        id:13,
        name: "DUNK LOW CHAMPIONSHIP RED",
        price: 165,
        category: "Nike",
        img: "https://katanasneaker.vercel.app/assets/img/SNEAKERWEPB3/NIKE%20DUNK%20LOW%20CHAMPIOSHIP%20RED.webp",
        rating: 4,
    
    },
    {
        id:14,
        name: "ADIDAS FORUM LOW",
        price: 90,
        category: "Adidas",
        img: "https://katanasneaker.vercel.app/assets/img/SNEAKERWEPB3/ADIDAS%20FORUM%20LOW.webp",
        rating: 5,
    },
    {
        id:15,
        name: "JORDAN 1 DIOR",
        price: 7000,
        category: "Air Jordan",
        img: "https://katanasneaker.vercel.app/assets/img/SNEAKERWEPB3/jordan1dior.webp",
        rating: 10,
    
    },
    {
        id:16,
        name: "ADIDAS FORUM BAD BUNNY" ,
        price: 120,
        category: "Adidas",
        img: "https://katanasneaker.vercel.app/assets/img/SNEAKERWEPB3/adidasforumbadbunny.webp",
        rating: 10,
    },
    {
        id:17,
        name: "YEEZY BOOST 700 V2",
        price: 373,
        category: "Yeezy",
        img: "https://katanasneaker.vercel.app/assets/img/SNEAKERWEPB3/YEEZY%20BOOST%20700%20V2.webp",
        rating: 9,
    
    },
    {
        id:19,
        name: "YEEZY BOOST 700 ENFALME",
        price: 21000,
        category: "Nike",
        img: "https://katanasneaker.vercel.app/assets/img/SNEAKERWEPB3/YEEZY%20BOOST%20700%20ENFLAME%20%20AMBER.webp",
        rating: 9,
    
    },
    {
        id:20,
        name: "DUNK LOW SEAN CLIVER",
        price: 480,
        category: "Nike",
        img: "https://katanasneaker.vercel.app/assets/img/SNEAKERWEPB3/NIKE%20SB%20DUNK%20LOW%20SEAN%20CLIVER.webp",
        rating: 6,
    
    },
    {
        id:21,
        name: "AIR JORDAN 3 RETRO UNC",
        price: 430,
        category: "Air Jordan",
        img: "https://katanasneaker.vercel.app/assets/img/SNEAKERWEPB3/AIR%20JORDAN%203%20RETRO%20UNC.webp",
        rating: 6,
    },
    {
        id:23,
        name: "AIR JORDAN 3 RETRO COOL GREY",
        price: 230,
        category: "Air Jordan",
        img: "https://katanasneaker.vercel.app/assets/img/SNEAKERWEPB3/AIR%20JORDAN%203%20RETRO%20COOL%20GREY.webp",
        rating: 8,
    },
    {
        id:24,
        name: "AIR MAX 1 CONCEPTS MELLOW",
        price: 130,
        category: "Nike",
        img: "https://katanasneaker.vercel.app/assets/img/SNEAKERWEPB3/AIRMAX%201%20CONCEPTS%20MELLOW.webp",
        rating: 4,
    },
    {
        id:25,
        name: "NIKE VAPORWAFFLE SACAI",
        price: 269,
        category: "Nike",
        img: "https://katanasneaker.vercel.app/assets/img/SNEAKERWEPB3/VAPORWAFFLE%20SACAI.webp",
        rating: 3,
    },
    {
        id:26,
        name: "AIR JORDAN 1 RETRO OFF WHITE",
        price: 1450,
        category: "Off white",
        img: "https://katanasneaker.vercel.app/assets/img/SNEAKERWEPB3/AIR%20JORDAN%201%20RETRO%20HIGH%20OFF%20WHITE.webp",
        rating: 10,
    },
    {
        id:27,
        name: "AIR JORDAN 5 RETRO EASTER",
        price: 130,
        category: "Air Jordan",
        img: "https://katanasneaker.vercel.app/assets/img/SNEAKERWEPB3/AIR%20JORDAN%205%20RETROEASTER.webp",
        rating: 7,
    },
    {
        id:28,
        name: "YEEZY BOOST 700 V2 VANTA",
        price: 310,
        category: "Yeezy",
        img: "https://katanasneaker.vercel.app/assets/img/SNEAKERWEPB3/YEEZY%20BOOST%20700%20V2%20VANTA.webp",
        rating: 10,
    },

    ];

    export default sneakerData